Type of library is SHARED
PickNikRobotics/RSL pull request #61
Opened 2022-11-11 17:52 UTC by tylerjw

It is a standard in Debian to package libraries as shared libraries and
only optionally provide a static library.
Reference:
https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#static-libraries

The reasons for building as a SHARED library by default are:
- Shared libraries can be updated without rebuilding all packages that
  depend on them.
- Shared libraries can be used as dependencies to other shared
  libraries (fPIC is enabled by default on SHARED libraries).
- Shared libraries result in smaller installs because the code from each
  library is not copied into each binary.

The disadvantage of shared libraries is that the compiler is restricted
from making certain types of optimizations, such as inlining.
Note that these sorts of optimizations only apply to code that is
actually in the library and not provided by a header.
In our case, the only functions that are included in the library are:
- rng
- random_unit_quaternion

The STL is typically linked as a shared library, and the special case is
using it as a static library.
If some user has the requirement to use RSL as a static library, I think
it is reasonable that they would fork it and change the way it is built or
provide a PR to make it build as both a static and shared library.

2022-11-11 20:15 UTC, ChrisThrasher commented
This is the wrong solution. If Debian distributors want shared libraries they can easily ask CMake for a shared library.

2022-11-11 22:07 UTC, tylerjw commented
> This is the wrong solution. If Debian distributors want shared libraries they can easily ask CMake for a shared library.

As we discussed on the phone, this is something you might be able to contribute to Debian. For now, though, this is the best solution for libraries being packaged by ROS until Debain.

2022-11-14 00:18 UTC, ChrisThrasher commented
For the record, what you told me is that the Debian packaging tooling lacks the ability or willingness to add `-DBUILD_SHARED_LIBS=ON` to the CMake configuration command so we're forced to work around that with hacks like this. Is there some written record of that limitation? Perhaps a GitHub issue or bug tracker item mentioning this shortcoming? Surely hundreds of other have run into this issue so I'd expect there to be something we can cite in this PR.

2022-11-14 00:20 UTC, ChrisThrasher commented
> If some user has the requirement to use RSL as a static library, I think
it is reasonable that they would fork it and change the way it is built or
provide a PR to make it build as both a static and shared library.

This is not a reasonable request. It's a technically possible thing that users can do, but it's entirely unreasonable to force users to patch RSL to achieve this. For that reason I'd rather we change the default value of `BUILD_SHARED_LIBS` so that Debian packagers stop patching this library but users who do want static libraries can still get that.

```cmake
option(BUILD_SHARED_LIBS ON "Build shared libraries")
```

2022-11-14 00:34 UTC, ChrisThrasher requested changes

2022-11-14 00:34 UTC, ChrisThrasher commented on CMakeLists.txt
> +add_library(rsl SHARED
```suggestion
# Default to shared libraries to work around the Debian ecosystem's inability to specify BUILD_SHARED_LIBS at configuration :(
option(BUILD_SHARED_LIBS ON "Build shared libraries")

add_library(rsl
```

2022-11-14 04:48 UTC, ChrisThrasher approved these changes

2022-11-14 06:52 UTC, merged

2022-11-14 07:30 UTC, jspricke commented
> For the record, what you told me is that the Debian packaging tooling lacks the ability or willingness to add `-DBUILD_SHARED_LIBS=ON` to the CMake configuration command

For the record, this is not true. The tooling can set that quiet easily but it is not set by default. For ROS we agreed on using the default flags provided by Debian, see: https://github.com/ros-infrastructure/bloom/issues/327. So I would urge you to open a bug with Debian to discuss this. Use `reportbug debhelper` on any Debian system to do so.

2022-11-14 07:42 UTC, jspricke commented
To give some more motivation, the default flags are defined here: https://sources.debian.org/src/debhelper/13.10.1/lib/Debian/Debhelper/Buildsystem/cmake.pm/?hl=197#L14
And I did not any discussion on `DBUILD_SHARED_LIBS`. So it basically only needs the bug report and some project consensus to implement this.